sonar.projectKey=vitaly-zdanevich_everpublich
sonar.organization=vitaly-zdanevich
sonar.sources=src
sonar.tests=tests
sonar.rust.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=target/**,build/**,.tools/**,coverage/**
