variable "aws_region" {
  type        = string
  description = "AWS region for Lambda, DynamoDB, S3, EventBridge, and ACM certificate validation."
  default     = "us-east-1"
}

variable "project_name" {
  type        = string
  description = "Name prefix for AWS resources."
  default     = "everpublich"
}

variable "api_lambda_zip_path" {
  type        = string
  description = "Path to the OAuth/admin Lambda zip generated by scripts/build-lambda.sh."
  default     = "../build/everpublich-lambda.zip"
}

variable "worker_lambda_zip_path" {
  type        = string
  description = "Path to the scheduled worker Lambda zip generated by scripts/build-lambda.sh."
  default     = "../build/everpublich-worker.zip"
}

variable "base_domain" {
  type        = string
  description = "Root domain for per-user subdomains, for example everpublich.com."
}

variable "route53_zone_id" {
  type        = string
  description = "Optional Route53 hosted zone ID. Leave empty if the TLD is registered outside AWS and DNS is managed elsewhere."
  default     = ""
}

variable "acm_certificate_arn" {
  type        = string
  description = "Optional us-east-1 ACM certificate ARN for the root domain and wildcard subdomains."
  default     = ""
}

variable "builder_users" {
  type = map(object({
    subdomain = string
  }))
  description = "Per-user builder Lambdas to create. Key is user_id; subdomain is used for routing metadata."
  default     = {}
}

variable "evernote_consumer_key" {
  type        = string
  description = "Evernote OAuth consumer key."
  sensitive   = true
  default     = ""
}

variable "evernote_consumer_secret" {
  type        = string
  description = "Evernote OAuth consumer secret."
  sensitive   = true
  default     = ""
}

variable "evernote_service_account_token" {
  type        = string
  description = "Optional token for the service Evernote account that receives read-only shared notebooks."
  sensitive   = true
  default     = ""
}

variable "token_secret" {
  type        = string
  description = "At least 32 characters. Used to encrypt OAuth tokens without KMS in the MVP."
  sensitive   = true
}

variable "admin_secret" {
  type        = string
  description = "Secret used to sign browser admin tokens."
  sensitive   = true
}

variable "github_oauth_client_id" {
  type        = string
  description = "GitHub OAuth app client ID."
  default     = ""
}

variable "github_oauth_client_secret" {
  type        = string
  description = "GitHub OAuth app client secret."
  sensitive   = true
  default     = ""
}

variable "support_email" {
  type        = string
  description = "Support email shown in the admin panel."
  default     = "zdanevich.vitaly@ya.ru"
}

variable "support_telegram" {
  type        = string
  description = "Support Telegram link shown in the admin panel."
  default     = "https://t.me/vitaly_zdanevich"
}

variable "support_tickets" {
  type        = string
  description = "Support issue tracker link shown in the admin panel."
  default     = "https://github.com/vitaly-zdanevich/everpublich/issues"
}

variable "lambda_memory_size_mb" {
  type        = number
  description = "Lambda memory for API and worker functions."
  default     = 3008
}

variable "lambda_timeout_seconds" {
  type        = number
  description = "Lambda timeout. Build workers use the Lambda maximum."
  default     = 900
}

variable "lambda_ephemeral_storage_mb" {
  type        = number
  description = "Lambda /tmp size for full site regeneration."
  default     = 10240
}
