//! Zola source tree generation.

use crate::models::{IndexMode, Post, PostKind, Resource, SearchMode, SiteSettings, UserItem};
use crate::slug::slugify;
use anyhow::{Context, Result};
use chrono::{Datelike, NaiveDate};
use html_escape::{
	decode_html_entities, encode_double_quoted_attribute, encode_single_quoted_attribute,
	encode_text,
};
use percent_encoding::{AsciiSet, CONTROLS, utf8_percent_encode};
use quick_xml::Reader;
use quick_xml::events::{BytesStart, Event};
use regex::Regex;
use serde_json::json;
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::OnceLock;

const URL_PATH_SEGMENT_ENCODE: &AsciiSet = &CONTROLS
	.add(b' ')
	.add(b'"')
	.add(b'#')
	.add(b'%')
	.add(b'<')
	.add(b'>')
	.add(b'?')
	.add(b'`')
	.add(b'{')
	.add(b'}');

#[derive(Debug, Clone, PartialEq, Eq)]
/// Summary of a generated Zola source tree.
pub struct GeneratedSite {
	/// Zola source root written by the generator.
	pub root: PathBuf,
	/// Number of blog posts written.
	pub posts: usize,
	/// Number of dedicated pages written.
	pub pages: usize,
	/// Number of podcast items written.
	pub podcast_items: usize,
}

#[derive(Debug, Clone, Default, PartialEq, Eq)]
struct NotebookSiteConfig {
	nav_tags: Vec<NavTagLink>,
	inline_css: String,
	inline_js: String,
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct NavTagLink {
	name: String,
	label: String,
	slug: String,
	title: String,
}

/// Write a complete Zola source tree. The caller should run `zola build` and
/// sync `public/` to the configured static hosting target.
pub fn write_zola_site(root: &Path, user: &UserItem, posts: &[Post]) -> Result<GeneratedSite> {
	fs::create_dir_all(root).with_context(|| format!("failed to create {}", root.display()))?;
	fs::create_dir_all(root.join("content/posts"))?;
	fs::create_dir_all(root.join("content/pages"))?;
	fs::create_dir_all(root.join("templates/shortcodes"))?;
	fs::create_dir_all(root.join("templates/tags"))?;
	fs::create_dir_all(root.join("static"))?;

	let notebook_config = notebook_site_config(posts);
	let has_about_page = posts.iter().any(|post| post.kind == PostKind::About);
	let has_tags_page = posts.iter().any(|post| !post.tags.is_empty());
	write_file(
		&root.join("config.toml"),
		&config_toml(
			&user.settings,
			has_about_page,
			has_tags_page,
			&notebook_config,
		),
	)?;
	write_file(
		&root.join("content/_index.md"),
		&root_index_md(&user.settings),
	)?;
	write_file(&root.join("content/posts/_index.md"), POSTS_INDEX_MD)?;
	write_templates(root, &notebook_config)?;
	write_file(&root.join("static/style.css"), STYLE_CSS)?;
	write_file(&root.join("static/search.js"), SEARCH_JS)?;
	if posts.iter().any(|post| post.body.contains("stl_viewer(")) {
		write_file(&root.join("static/stl-viewer.js"), STL_VIEWER_JS)?;
	}
	if posts
		.iter()
		.any(|post| post.body.contains("three_model_viewer("))
	{
		write_file(
			&root.join("static/three-model-viewer.js"),
			THREE_MODEL_VIEWER_JS,
		)?;
	}
	write_search_metadata(root, &user.settings, posts)?;
	if let Some(custom_css) = user
		.settings
		.custom_css
		.as_deref()
		.filter(|css| !css.trim().is_empty())
	{
		write_file(&root.join("static/custom.css"), custom_css)?;
	}

	let mut post_count = 0;
	let mut page_count = 0;
	let mut day_posts = BTreeMap::<NaiveDate, Vec<&Post>>::new();

	for post in posts {
		match post.kind {
			PostKind::BlogPost => {
				write_post(root, post)?;
				day_posts
					.entry(post.date.date_naive())
					.or_default()
					.push(post);
				post_count += 1;
			}
			PostKind::Page | PostKind::About => {
				write_page(root, post)?;
				page_count += 1;
			}
			PostKind::NavTag | PostKind::Config => {}
		}
	}

	write_calendar(root, &day_posts, &user.settings.base_url)?;
	write_day_pages(root, &day_posts, &user.settings.base_url)?;
	write_month_pages(root, &day_posts, &user.settings.base_url)?;
	if !has_tags_page {
		write_empty_tags_page(root)?;
	}
	let podcast_items = write_podcast(root, &user.settings, posts)?;

	Ok(GeneratedSite {
		root: root.to_path_buf(),
		posts: post_count,
		pages: page_count,
		podcast_items,
	})
}

fn write_file(path: &Path, content: &str) -> Result<()> {
	if let Some(parent) = path.parent() {
		fs::create_dir_all(parent)?;
	}
	fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))
}

fn config_toml(
	settings: &SiteSettings,
	has_about_page: bool,
	has_tags_page: bool,
	notebook_config: &NotebookSiteConfig,
) -> String {
	let feeds = "generate_feeds = true\nfeed_filenames = [\"rss.xml\"]\n";
	let theme = settings
		.zola_theme
		.as_ref()
		.map(|t| format!("theme = \"{}\"\n", toml_escape(t)))
		.unwrap_or_default();
	let search = matches!(settings.search_mode, SearchMode::ZolaStatic);
	let google_search = matches!(settings.search_mode, SearchMode::Google);
	let has_custom_css = settings
		.custom_css
		.as_deref()
		.map(|css| !css.trim().is_empty())
		.unwrap_or(false);
	format!(
		r#"# Generated by Everpublich; regenerated on every build.
base_url = "{base_url}"
title = "{title}"
description = "Evernote notebook published as a static Zola website."
default_language = "en"
compile_sass = false
build_search_index = {search}
minify_html = true
{feeds}{theme}
taxonomies = [
  {{ name = "tags", feed = true }},
]

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_referrer = true

[extra]
generator = "everpublich"
index_mode = "{index_mode}"
search_static = {search}
search_google = {google_search}
expand_widgets = {expand_widgets}
has_custom_css = {has_custom_css}
has_about_page = {has_about_page}
has_tags_page = {has_tags_page}
nav_tags = {nav_tags}
google_analytics_id = {google_analytics}
yandex_metrica_id = {yandex_metrica}
"#,
		base_url = toml_escape(&settings.base_url),
		title = toml_escape(&settings.title),
		search = search,
		feeds = feeds,
		theme = theme,
		index_mode = match settings.index_mode {
			IndexMode::FullPosts => "full_posts",
			IndexMode::TitlesOnly => "titles_only",
		},
		google_search = google_search,
		expand_widgets = settings.expand_widgets,
		has_custom_css = has_custom_css,
		has_about_page = has_about_page,
		has_tags_page = has_tags_page,
		nav_tags = nav_tags_toml(&notebook_config.nav_tags),
		google_analytics = option_toml(settings.google_analytics_id.as_deref()),
		yandex_metrica = option_toml(settings.yandex_metrica_id.as_deref()),
	)
}

fn root_index_md(settings: &SiteSettings) -> String {
	let template = if settings.zola_theme.is_none() {
		"template = \"index.html\"\n"
	} else {
		""
	};
	format!("+++\nsort_by = \"date\"\npaginate_by = 20\n{template}+++\n")
}

const POSTS_INDEX_MD: &str = "+++\nsort_by = \"date\"\ntransparent = true\npaginate_by = 20\n+++\n";

fn write_post(root: &Path, post: &Post) -> Result<()> {
	let dir = root.join("content/posts").join(&post.slug);
	let mut md = front_matter(post, Some("post.html"), None);
	md.push_str(&post.body);
	md.push('\n');
	write_file(&dir.join("index.md"), &md)
}

fn write_page(root: &Path, post: &Post) -> Result<()> {
	let name = if post.kind == PostKind::About {
		"about".to_string()
	} else {
		post.slug.clone()
	};
	let dir = root.join("content/pages").join(name);
	let mut md = front_matter(post, Some("page.html"), Some(&post.slug));
	md.push_str(&post.body);
	md.push('\n');
	write_file(&dir.join("index.md"), &md)
}

fn front_matter(post: &Post, template: Option<&str>, path: Option<&str>) -> String {
	let mut out = String::new();
	out.push_str("+++\n");
	let _ = writeln!(out, "title = \"{}\"", toml_escape(&post.title));
	let _ = writeln!(out, "date = {}", post.date.to_rfc3339());
	if let Some(template) = template {
		let _ = writeln!(out, "template = \"{template}\"");
	}
	if let Some(path) = path {
		let _ = writeln!(out, "path = \"{}\"", toml_escape(path));
	}
	let _ = writeln!(out, "slug = \"{}\"", toml_escape(&post.slug));
	out.push_str("\n[taxonomies]\n");
	let tags = post
		.tags
		.iter()
		.map(|t| format!("\"{}\"", toml_escape(t)))
		.collect::<Vec<_>>()
		.join(", ");
	let _ = writeln!(out, "tags = [{tags}]");
	out.push_str("\n[extra]\n");
	let _ = writeln!(out, "guid = \"{}\"", toml_escape(&post.guid));
	let _ = writeln!(out, "day = \"{}\"", post.date.format("%Y-%m-%d"));
	let _ = writeln!(
		out,
		"nav_title = \"{}\"",
		toml_escape(&post_nav_title(post))
	);
	out.push_str("+++\n\n");
	out
}

fn write_calendar(
	root: &Path,
	day_posts: &BTreeMap<NaiveDate, Vec<&Post>>,
	base_url: &str,
) -> Result<()> {
	let mut html = String::new();
	html.push_str(
		"+++\ntitle = \"Calendar\"\npath = \"calendar\"\ntemplate = \"calendar.html\"\n+++\n\n",
	);
	html.push_str("<div class=\"calendar-years\">\n");

	let years = day_posts
		.keys()
		.map(|d| d.year())
		.collect::<BTreeSet<_>>()
		.into_iter()
		.rev()
		.collect::<Vec<_>>();

	for year in years {
		let _ = writeln!(html, "<h2>{year}</h2><div class=\"calendar-months\">");
		for month in 1..=12 {
			let days = day_posts
				.iter()
				.filter(|(day, _)| day.year() == year && day.month() == month)
				.collect::<Vec<_>>();
			if days.is_empty() {
				continue;
			}
			let month_name = month_name(month);
			let month_url = site_url(base_url, &format!("month/{year}-{month:02}/"));
			let _ = writeln!(
				html,
				"<section class=\"calendar-month\"><h3><a href='{}'>{month_name}</a></h3><div class=\"calendar-days\">",
				encode_single_quoted_attribute(&month_url)
			);
			for (day, posts) in days {
				let count = posts.len();
				let url = site_url(base_url, &format!("day/{day}/"));
				let _ = writeln!(
					html,
					"<a class='{}' href='{}' title='{}'>{}</a>",
					calendar_day_class(count),
					encode_single_quoted_attribute(&url),
					encode_calendar_title_attribute(&calendar_day_title(posts)),
					day.day(),
				);
			}
			html.push_str("</div></section>\n");
		}
		html.push_str("</div>\n");
	}
	html.push_str("</div>\n");
	write_file(&root.join("content/pages/calendar.md"), &html)
}

fn calendar_day_class(count: usize) -> &'static str {
	match count {
		0 | 1 => "calendar-day calendar-day--one",
		2 => "calendar-day calendar-day--two",
		_ => "calendar-day calendar-day--many",
	}
}

fn post_count_label(count: usize) -> String {
	if count == 1 {
		"1 post".to_string()
	} else {
		format!("{count} posts")
	}
}

/// Build the browser tooltip for a calendar day link.
fn calendar_day_title(posts: &[&Post]) -> String {
	let titles = posts
		.iter()
		.map(|post| post.title.trim())
		.filter(|title| !title.is_empty())
		.collect::<Vec<_>>()
		.join("\n\n");
	if titles.is_empty() {
		post_count_label(posts.len())
	} else {
		format!("{}\n\n{titles}", post_count_label(posts.len()))
	}
}

fn day_archive_title(day: &NaiveDate, posts: &[&Post]) -> String {
	let titles = posts
		.iter()
		.map(|post| post.title.trim())
		.filter(|title| !title.is_empty())
		.collect::<Vec<_>>()
		.join("\n\n");
	if titles.is_empty() {
		format!("{} {}", month_name(day.month()), day.day())
	} else {
		format!("{} {}\n\n{titles}", month_name(day.month()), day.day())
	}
}

fn encode_calendar_title_attribute(title: &str) -> String {
	encode_single_quoted_attribute(title).replace('\n', "&#10;")
}

fn month_name(month: u32) -> &'static str {
	match month {
		1 => "January",
		2 => "February",
		3 => "March",
		4 => "April",
		5 => "May",
		6 => "June",
		7 => "July",
		8 => "August",
		9 => "September",
		10 => "October",
		11 => "November",
		12 => "December",
		_ => "",
	}
}

fn write_day_pages(
	root: &Path,
	day_posts: &BTreeMap<NaiveDate, Vec<&Post>>,
	base_url: &str,
) -> Result<()> {
	let days = day_posts.iter().collect::<Vec<_>>();
	for (index, (day, posts)) in days.iter().copied().enumerate() {
		let dir = root.join("content/day").join(day.to_string());
		let mut md = String::new();
		md.push_str("+++\n");
		let _ = writeln!(md, "title = \"{}\"", day);
		let _ = writeln!(md, "path = \"day/{}\"", day);
		md.push_str("template = \"day.html\"\n");
		md.push_str("+++\n\n");
		for post in posts {
			write_day_post(&mut md, post, base_url);
		}
		write_day_nav(
			&mut md,
			base_url,
			index
				.checked_sub(1)
				.and_then(|previous| days.get(previous))
				.copied(),
			days.get(index + 1).copied(),
		);
		write_file(&dir.join("index.md"), &md)?;
	}
	Ok(())
}

fn write_day_nav(
	md: &mut String,
	base_url: &str,
	previous: Option<(&NaiveDate, &Vec<&Post>)>,
	next: Option<(&NaiveDate, &Vec<&Post>)>,
) {
	if previous.is_none() && next.is_none() {
		return;
	}
	md.push_str("<nav class='post-nav' aria-label='Day navigation'>\n");
	if let Some((day, posts)) = previous {
		write_day_nav_link(md, base_url, "prev", "Previous day", day, posts);
	}
	if let Some((day, posts)) = next {
		write_day_nav_link(md, base_url, "next", "Next day", day, posts);
	}
	md.push_str("</nav>\n");
}

fn write_day_nav_link(
	md: &mut String,
	base_url: &str,
	direction: &str,
	label: &str,
	day: &NaiveDate,
	posts: &[&Post],
) {
	let url = site_url(base_url, &format!("day/{day}/"));
	let title = day_archive_title(day, posts);
	let _ = writeln!(
		md,
		"<a class='post-nav__link post-nav__link--{}' href='{}' title='{}'><span>{}</span><strong>{}</strong></a>",
		encode_single_quoted_attribute(direction),
		encode_single_quoted_attribute(&url),
		encode_calendar_title_attribute(&title),
		encode_text(label),
		encode_text(&format!("{} {}", month_name(day.month()), day.day()))
	);
}

fn write_month_pages(
	root: &Path,
	day_posts: &BTreeMap<NaiveDate, Vec<&Post>>,
	base_url: &str,
) -> Result<()> {
	let mut month_posts = BTreeMap::<(i32, u32), Vec<&Post>>::new();
	for (day, posts) in day_posts {
		month_posts
			.entry((day.year(), day.month()))
			.or_default()
			.extend(posts.iter().copied());
	}

	for ((year, month), posts) in month_posts {
		let month_key = format!("{year}-{month:02}");
		let dir = root.join("content/month").join(&month_key);
		let mut md = String::new();
		md.push_str("+++\n");
		let _ = writeln!(md, "title = \"{} {year}\"", month_name(month));
		let _ = writeln!(md, "path = \"month/{month_key}\"");
		md.push_str("template = \"day.html\"\n");
		md.push_str("+++\n\n");
		for post in posts {
			write_day_post(&mut md, post, base_url);
		}
		write_file(&dir.join("index.md"), &md)?;
	}
	Ok(())
}

fn write_day_post(md: &mut String, post: &Post, base_url: &str) {
	let day = post.date.format("%Y-%m-%d");
	let post_url = site_url(base_url, &format!("posts/{}/", post.slug));
	let day_url = site_url(base_url, &format!("day/{day}/"));
	let time = post.date.format("%H:%M:%S").to_string();
	let _ = writeln!(md, "<article class='post'>");
	let _ = writeln!(
		md,
		"<h2><a href='{}'>{}</a></h2>",
		encode_single_quoted_attribute(&post_url),
		encode_text(&post.title)
	);
	let _ = writeln!(
		md,
		"<p class='meta'><a href='{}' title='{}'><time>{day}</time></a></p>",
		encode_single_quoted_attribute(&day_url),
		encode_single_quoted_attribute(&time),
	);
	let _ = writeln!(md, "<div class='content'>");
	md.push_str(&post.body);
	md.push_str("\n</div>\n");
	if !post.tags.is_empty() {
		md.push_str("<p class='tags'>");
		for tag in &post.tags {
			let tag_url = site_url(base_url, &format!("tags/{}/", slugify(tag)));
			let _ = write!(
				md,
				"<a href='{}'>#{}</a>",
				encode_single_quoted_attribute(&tag_url),
				encode_text(tag)
			);
		}
		md.push_str("</p>\n");
	}
	md.push_str("</article>\n");
}

fn site_url(base_url: &str, path: &str) -> String {
	format!(
		"{}/{}",
		base_url.trim_end_matches('/'),
		path.trim_start_matches('/')
	)
}

fn write_empty_tags_page(root: &Path) -> Result<()> {
	write_file(
		&root.join("content/pages/tags.md"),
		"+++\ntitle = \"Tags\"\npath = \"tags\"\ntemplate = \"page.html\"\n+++\n\nNo tags found in the synced Evernote cache.\n",
	)
}

fn write_search_metadata(root: &Path, settings: &SiteSettings, posts: &[Post]) -> Result<()> {
	let mut metadata = serde_json::Map::new();
	for post in posts {
		let path = match post.kind {
			PostKind::BlogPost => format!("posts/{}/", post.slug),
			PostKind::Page => format!("{}/", post.slug),
			PostKind::About => "about/".to_string(),
			PostKind::NavTag | PostKind::Config => continue,
		};
		metadata.insert(
			site_url(&settings.base_url, &path),
			json!({
				"date": post.date.format("%Y-%m-%d").to_string(),
			}),
		);
	}
	let js = format!(
		"window.everpublichSearchMetadata = {};\n",
		serde_json::to_string(&metadata)?
	);
	write_file(&root.join("static/search_metadata.js"), &js)
}

fn write_podcast(root: &Path, settings: &SiteSettings, posts: &[Post]) -> Result<usize> {
	let mut items = String::new();
	let mut count = 0usize;
	for post in posts.iter().filter(|post| {
		post.tags
			.iter()
			.any(|tag| tag.eq_ignore_ascii_case("podcast"))
	}) {
		let Some(audio) = post.resources.iter().find(|r| r.mime.starts_with("audio/")) else {
			continue;
		};
		count += 1;
		items.push_str(&podcast_item_xml(settings, post, audio));
	}

	let xml = format!(
		r#"<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">
<channel>
<title>{}</title>
<link>{}</link>
<description>Podcast feed generated from Evernote notes tagged podcast.</description>
<language>en</language>
<generator>Everpublich</generator>
<itunes:author>{}</itunes:author>
<itunes:summary>Podcast feed generated from Evernote notes tagged podcast.</itunes:summary>
<itunes:explicit>false</itunes:explicit>
{}
</channel>
</rss>
"#,
		encode_text(&settings.title),
		encode_text(&settings.base_url),
		encode_text(&settings.title),
		items
	);
	validate_podcast_xml(&xml, count)?;
	write_file(&root.join("static/podcast.xml"), &xml)?;
	Ok(count)
}

/// Render one podcast feed item and keep media URLs absolute for podcast
/// clients that do not resolve relative paths against the feed URL.
fn podcast_item_xml(settings: &SiteSettings, post: &Post, audio: &Resource) -> String {
	let post_url = site_url(&settings.base_url, &format!("posts/{}/", post.slug));
	let audio_url = site_url(
		&settings.base_url,
		&format!(
			"posts/{}/{}",
			post.slug,
			percent_encode_path_segment(&audio.file_name)
		),
	);
	let description = podcast_description(post);
	format!(
		"<item>\
<title>{}</title>\
<link>{}</link>\
<guid isPermaLink=\"true\">{}</guid>\
<pubDate>{}</pubDate>\
<description>{}</description>\
<itunes:title>{}</itunes:title>\
<itunes:author>{}</itunes:author>\
<itunes:subtitle>{}</itunes:subtitle>\
<itunes:summary>{}</itunes:summary>\
<itunes:explicit>false</itunes:explicit>\
{}<itunes:episodeType>full</itunes:episodeType>\
<enclosure url=\"{}\" type=\"{}\" length=\"0\"/>\
</item>\n",
		encode_text(&post.title),
		encode_text(&post_url),
		encode_text(&post_url),
		post.date.to_rfc2822(),
		encode_text(&description),
		encode_text(&post.title),
		encode_text(&settings.title),
		encode_text(&podcast_subtitle(&description)),
		encode_text(&description),
		podcast_keywords_xml(post),
		encode_double_quoted_attribute(&audio_url),
		encode_double_quoted_attribute(&audio.mime),
	)
}

fn podcast_subtitle(description: &str) -> String {
	truncate_chars(description, 255)
}

fn podcast_keywords_xml(post: &Post) -> String {
	let keywords = post
		.tags
		.iter()
		.filter(|tag| !tag.eq_ignore_ascii_case("podcast"))
		.map(String::as_str)
		.collect::<Vec<_>>();
	if keywords.is_empty() {
		String::new()
	} else {
		format!(
			"<itunes:keywords>{}</itunes:keywords>",
			encode_text(&keywords.join(", "))
		)
	}
}

fn podcast_description(post: &Post) -> String {
	let text = post_plain_text(&post.body);
	if text.is_empty() {
		truncate_chars(post.title.trim(), 4000)
	} else {
		truncate_chars(&text, 4000)
	}
}

fn percent_encode_path_segment(segment: &str) -> String {
	utf8_percent_encode(segment, URL_PATH_SEGMENT_ENCODE).to_string()
}

/// Parse the generated feed and fail the build when required podcast fields
/// are missing.
fn validate_podcast_xml(xml: &str, expected_items: usize) -> Result<()> {
	let mut reader = Reader::from_str(xml);
	reader.config_mut().trim_text(true);
	let mut root_ok = false;
	let mut channel = ChannelValidation::default();
	let mut current_item: Option<ItemValidation> = None;
	let mut items = Vec::new();
	let mut current_text_tag: Option<Vec<u8>> = None;

	loop {
		match reader.read_event()? {
			Event::Start(element) => {
				let name = element.name().as_ref().to_vec();
				if name.as_slice() == b"rss" {
					root_ok = attr_value(&element, b"xmlns:itunes").as_deref()
						== Some("http://www.itunes.com/dtds/podcast-1.0.dtd");
				} else if name.as_slice() == b"item" {
					current_item = Some(ItemValidation::default());
				} else {
					current_text_tag = Some(name);
				}
			}
			Event::Empty(element) if element.name().as_ref() == b"enclosure" => {
				let Some(item) = current_item.as_mut() else {
					anyhow::bail!("podcast enclosure outside item");
				};
				item.enclosures += 1;
				item.audio_enclosure = attr_value(&element, b"type")
					.as_deref()
					.is_some_and(|mime| mime.starts_with("audio/"))
					&& attr_value(&element, b"url")
						.as_deref()
						.is_some_and(|url| url.starts_with("https://"));
			}
			Event::Text(text) => {
				let Some(tag) = current_text_tag.as_deref() else {
					continue;
				};
				let text = text.decode()?.trim().to_string();
				if text.is_empty() {
					continue;
				}
				if let Some(item) = current_item.as_mut() {
					item.mark_text(tag);
				} else {
					channel.mark_text(tag);
				}
			}
			Event::End(element) => {
				let name = element.name().as_ref().to_vec();
				if name.as_slice() == b"item" {
					let Some(item) = current_item.take() else {
						anyhow::bail!("podcast item end without start");
					};
					items.push(item);
				}
				if current_text_tag.as_deref() == Some(name.as_slice()) {
					current_text_tag = None;
				}
			}
			Event::Eof => break,
			_ => {}
		}
	}

	anyhow::ensure!(root_ok, "podcast feed missing iTunes RSS namespace");
	anyhow::ensure!(
		channel.is_valid(),
		"podcast channel is missing required metadata"
	);
	anyhow::ensure!(
		items.len() == expected_items,
		"podcast feed has {} item(s), expected {expected_items}",
		items.len()
	);
	for item in items {
		anyhow::ensure!(item.is_valid(), "podcast item is missing required metadata");
	}
	Ok(())
}

fn attr_value(element: &BytesStart, name: &[u8]) -> Option<String> {
	element.attributes().flatten().find_map(|attribute| {
		if attribute.key.as_ref() == name {
			Some(String::from_utf8_lossy(attribute.value.as_ref()).to_string())
		} else {
			None
		}
	})
}

#[derive(Default)]
struct ChannelValidation {
	title: bool,
	link: bool,
	description: bool,
	language: bool,
	generator: bool,
	itunes_author: bool,
	itunes_summary: bool,
	itunes_explicit: bool,
}

impl ChannelValidation {
	fn mark_text(&mut self, tag: &[u8]) {
		match tag {
			b"title" => self.title = true,
			b"link" => self.link = true,
			b"description" => self.description = true,
			b"language" => self.language = true,
			b"generator" => self.generator = true,
			b"itunes:author" => self.itunes_author = true,
			b"itunes:summary" => self.itunes_summary = true,
			b"itunes:explicit" => self.itunes_explicit = true,
			_ => {}
		}
	}

	fn is_valid(&self) -> bool {
		self.title
			&& self.link
			&& self.description
			&& self.language
			&& self.generator
			&& self.itunes_author
			&& self.itunes_summary
			&& self.itunes_explicit
	}
}

#[derive(Default)]
struct ItemValidation {
	title: bool,
	link: bool,
	guid: bool,
	pub_date: bool,
	description: bool,
	itunes_title: bool,
	itunes_author: bool,
	itunes_subtitle: bool,
	itunes_summary: bool,
	itunes_explicit: bool,
	itunes_episode_type: bool,
	enclosures: usize,
	audio_enclosure: bool,
}

impl ItemValidation {
	fn mark_text(&mut self, tag: &[u8]) {
		match tag {
			b"title" => self.title = true,
			b"link" => self.link = true,
			b"guid" => self.guid = true,
			b"pubDate" => self.pub_date = true,
			b"description" => self.description = true,
			b"itunes:title" => self.itunes_title = true,
			b"itunes:author" => self.itunes_author = true,
			b"itunes:subtitle" => self.itunes_subtitle = true,
			b"itunes:summary" => self.itunes_summary = true,
			b"itunes:explicit" => self.itunes_explicit = true,
			b"itunes:episodeType" => self.itunes_episode_type = true,
			_ => {}
		}
	}

	fn is_valid(&self) -> bool {
		self.title
			&& self.link
			&& self.guid
			&& self.pub_date
			&& self.description
			&& self.itunes_title
			&& self.itunes_author
			&& self.itunes_subtitle
			&& self.itunes_summary
			&& self.itunes_explicit
			&& self.itunes_episode_type
			&& self.enclosures == 1
			&& self.audio_enclosure
	}
}

fn write_templates(root: &Path, notebook_config: &NotebookSiteConfig) -> Result<()> {
	for (path, body) in [
		("templates/base.html", BASE_HTML),
		("templates/index.html", INDEX_HTML),
		("templates/post.html", POST_HTML),
		("templates/page.html", PAGE_HTML),
		("templates/calendar.html", CALENDAR_HTML),
		("templates/day.html", DAY_HTML),
		("templates/tags/list.html", TAGS_LIST_HTML),
		("templates/tags/single.html", TAGS_SINGLE_HTML),
		("templates/shortcodes/audio.html", AUDIO_SHORTCODE),
		("templates/shortcodes/video.html", VIDEO_SHORTCODE),
		("templates/shortcodes/ruffle.html", RUFFLE_SHORTCODE),
		(
			"templates/shortcodes/midi_player.html",
			MIDI_PLAYER_SHORTCODE,
		),
		(
			"templates/shortcodes/epub_viewer.html",
			EPUB_VIEWER_SHORTCODE,
		),
		(
			"templates/shortcodes/comic_viewer.html",
			COMIC_VIEWER_SHORTCODE,
		),
		(
			"templates/shortcodes/font_preview.html",
			FONT_PREVIEW_SHORTCODE,
		),
		(
			"templates/shortcodes/model_viewer.html",
			MODEL_VIEWER_SHORTCODE,
		),
		("templates/shortcodes/stl_viewer.html", STL_VIEWER_SHORTCODE),
		(
			"templates/shortcodes/three_model_viewer.html",
			THREE_MODEL_VIEWER_SHORTCODE,
		),
		("templates/shortcodes/youtube.html", YOUTUBE_SHORTCODE),
		("templates/shortcodes/vimeo.html", VIMEO_SHORTCODE),
		("templates/shortcodes/spotify.html", SPOTIFY_SHORTCODE),
		("templates/shortcodes/soundcloud.html", SOUNDCLOUD_SHORTCODE),
		("templates/shortcodes/genius.html", GENIUS_SHORTCODE),
		(
			"templates/shortcodes/apple_podcast.html",
			APPLE_PODCAST_SHORTCODE,
		),
		(
			"templates/shortcodes/yandex_music.html",
			YANDEX_MUSIC_SHORTCODE,
		),
		("templates/shortcodes/instagram.html", INSTAGRAM_SHORTCODE),
		("templates/shortcodes/pinterest.html", PINTEREST_SHORTCODE),
		("templates/shortcodes/rumble.html", RUMBLE_SHORTCODE),
		("templates/shortcodes/odysee.html", ODYSEE_SHORTCODE),
		("templates/shortcodes/bilibili.html", BILIBILI_SHORTCODE),
		("templates/shortcodes/tiktok.html", TIKTOK_SHORTCODE),
		("templates/shortcodes/steam.html", STEAM_SHORTCODE),
		(
			"templates/shortcodes/vk_playlist.html",
			VK_PLAYLIST_SHORTCODE,
		),
	] {
		write_file(&root.join(path), body)?;
	}
	write_file(
		&root.join("templates/notebook_config_head.html"),
		&notebook_config_head_template(notebook_config),
	)?;
	write_file(
		&root.join("templates/notebook_config_body.html"),
		&notebook_config_body_template(notebook_config),
	)?;
	Ok(())
}

fn notebook_config_head_template(notebook_config: &NotebookSiteConfig) -> String {
	if notebook_config.inline_css.trim().is_empty() {
		String::new()
	} else {
		format!(
			"<style>\n{}\n</style>\n",
			escape_inline_style(&notebook_config.inline_css)
		)
	}
}

fn notebook_config_body_template(notebook_config: &NotebookSiteConfig) -> String {
	if notebook_config.inline_js.trim().is_empty() {
		String::new()
	} else {
		format!(
			"<script>\n{}\n</script>\n",
			escape_inline_script(&notebook_config.inline_js)
		)
	}
}

fn escape_inline_style(css: &str) -> String {
	Regex::new("(?i)</style")
		.unwrap()
		.replace_all(css, "<\\/style")
		.into_owned()
}

fn escape_inline_script(js: &str) -> String {
	Regex::new("(?i)</script")
		.unwrap()
		.replace_all(js, "<\\/script")
		.into_owned()
}

fn toml_escape(s: &str) -> String {
	let mut escaped = String::new();
	for c in s.chars() {
		match c {
			'\\' => escaped.push_str("\\\\"),
			'"' => escaped.push_str("\\\""),
			'\n' => escaped.push_str("\\n"),
			'\r' => escaped.push_str("\\r"),
			'\t' => escaped.push_str("\\t"),
			c => escaped.push(c),
		}
	}
	escaped
}

fn option_toml(s: Option<&str>) -> String {
	s.map(|v| format!("\"{}\"", toml_escape(v)))
		.unwrap_or_else(|| "false".to_string())
}

fn nav_tags_toml(tags: &[NavTagLink]) -> String {
	if tags.is_empty() {
		return "[]".to_string();
	}
	let items = tags
		.iter()
		.map(|tag| {
			format!(
				"{{ name = \"{}\", label = \"{}\", slug = \"{}\", title = \"{}\" }}",
				toml_escape(&tag.name),
				toml_escape(&tag.label),
				toml_escape(&tag.slug),
				toml_escape(&tag.title)
			)
		})
		.collect::<Vec<_>>()
		.join(", ");
	format!("[{items}]")
}

fn notebook_site_config(posts: &[Post]) -> NotebookSiteConfig {
	let mut config = NotebookSiteConfig::default();
	for post in posts {
		match post.kind {
			PostKind::NavTag => {
				if let Some(tag) = post.title.trim().strip_prefix('#') {
					let name = tag.trim();
					if !name.is_empty() {
						config.nav_tags.push(NavTagLink {
							name: name.to_string(),
							label: format!("#{name}"),
							slug: slugify(name),
							title: post_plain_text(&post.body),
						});
					}
				}
			}
			PostKind::Config => {
				for block in config_code_blocks(&post.body) {
					match block.language.as_str() {
						"css" => push_snippet(&mut config.inline_css, &block.body),
						"js" | "javascript" => push_snippet(&mut config.inline_js, &block.body),
						_ => {}
					}
				}
			}
			PostKind::BlogPost | PostKind::Page | PostKind::About => {}
		}
	}
	config
}

fn push_snippet(out: &mut String, snippet: &str) {
	let snippet = snippet.trim();
	if snippet.is_empty() {
		return;
	}
	if !out.is_empty() {
		out.push_str("\n\n");
	}
	out.push_str(snippet);
}

#[derive(Debug, Clone, PartialEq, Eq)]
struct ConfigCodeBlock {
	language: String,
	body: String,
}

fn config_code_blocks(body: &str) -> Vec<ConfigCodeBlock> {
	let mut blocks = markdown_config_code_blocks(body);
	blocks.extend(html_config_code_blocks(body));
	blocks
}

fn markdown_config_code_blocks(body: &str) -> Vec<ConfigCodeBlock> {
	Regex::new(r"(?ms)(?:^|\n)```([A-Za-z0-9_-]+)\s*\n(.*?)\n```")
		.unwrap()
		.captures_iter(body)
		.filter_map(|caps| {
			Some(ConfigCodeBlock {
				language: caps.get(1)?.as_str().to_ascii_lowercase(),
				body: caps.get(2)?.as_str().to_string(),
			})
		})
		.collect()
}

fn html_config_code_blocks(body: &str) -> Vec<ConfigCodeBlock> {
	Regex::new(r#"(?is)<pre[^>]*>\s*<code([^>]*)>(.*?)</code>\s*</pre>"#)
		.unwrap()
		.captures_iter(body)
		.filter_map(|caps| {
			let language = html_code_language(caps.get(1).map(|m| m.as_str()).unwrap_or(""))?;
			Some(ConfigCodeBlock {
				language,
				body: decode_html_entities(caps.get(2)?.as_str()).to_string(),
			})
		})
		.collect()
}

fn html_code_language(attrs: &str) -> Option<String> {
	let class = Regex::new(r#"(?is)\bclass\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))"#)
		.unwrap()
		.captures(attrs)
		.and_then(|caps| caps.get(1).or_else(|| caps.get(2)).or_else(|| caps.get(3)))
		.map(|value| value.as_str().to_ascii_lowercase());
	let lang = class.as_deref().and_then(|class| {
		class.split_whitespace().find_map(|item| {
			item.strip_prefix("language-")
				.or_else(|| item.strip_prefix("lang-"))
		})
	});
	lang.or_else(|| {
		Regex::new(r#"(?is)\bdata-language\s*=\s*(?:"([^"]*)"|'([^']*)'|([^\s>]+))"#)
			.unwrap()
			.captures(attrs)
			.and_then(|caps| caps.get(1).or_else(|| caps.get(2)).or_else(|| caps.get(3)))
			.map(|value| value.as_str())
	})
	.map(|language| language.to_ascii_lowercase())
}

fn post_nav_title(post: &Post) -> String {
	let body = post_plain_text(&post.body);
	truncate_chars(&body, 1000)
}

fn post_plain_text(body: &str) -> String {
	let without_attachment_previews = attachment_preview_regex().replace_all(body, " ");
	let without_attachment_images =
		attachment_preview_image_regex().replace_all(&without_attachment_previews, " ");
	let with_line_breaks = block_boundary_regex().replace_all(&without_attachment_images, "\n");
	let without_shortcodes = shortcode_regex().replace_all(&with_line_breaks, " ");
	let without_tags = html_tag_regex().replace_all(&without_shortcodes, " ");
	decode_html_entities(&without_tags)
		.lines()
		.map(|line| line.split_whitespace().collect::<Vec<_>>().join(" "))
		.filter(|line| !line.is_empty())
		.collect::<Vec<_>>()
		.join("\n")
}

fn attachment_preview_regex() -> &'static Regex {
	static REGEX: OnceLock<Regex> = OnceLock::new();
	REGEX.get_or_init(|| {
		Regex::new(r#"(?is)<details\b[^>]*class=(?:"[^"]*\battachment-preview\b[^"]*"|'[^']*\battachment-preview\b[^']*')[^>]*>.*?</details>"#)
			.unwrap()
	})
}

fn attachment_preview_image_regex() -> &'static Regex {
	static REGEX: OnceLock<Regex> = OnceLock::new();
	REGEX.get_or_init(|| {
		Regex::new(r#"(?is)<figure\b[^>]*class=(?:"[^"]*\battachment-preview-image\b[^"]*"|'[^']*\battachment-preview-image\b[^']*')[^>]*>.*?</figure>"#)
			.unwrap()
	})
}

fn truncate_chars(text: &str, max: usize) -> String {
	if text.chars().count() <= max {
		return text.to_string();
	}
	let mut out = text.chars().take(max.saturating_sub(3)).collect::<String>();
	out.push_str("...");
	out
}

fn block_boundary_regex() -> &'static Regex {
	static REGEX: OnceLock<Regex> = OnceLock::new();
	REGEX.get_or_init(|| {
		Regex::new(r"(?i)</?(?:address|article|aside|blockquote|br|dd|div|dl|dt|figcaption|figure|footer|h[1-6]|header|hr|li|main|nav|ol|p|pre|section|table|tbody|td|tfoot|th|thead|tr|ul)\b[^>]*>")
			.unwrap()
	})
}

fn html_tag_regex() -> &'static Regex {
	static REGEX: OnceLock<Regex> = OnceLock::new();
	REGEX.get_or_init(|| Regex::new(r"(?s)<[^>]+>").unwrap())
}

fn shortcode_regex() -> &'static Regex {
	static REGEX: OnceLock<Regex> = OnceLock::new();
	REGEX.get_or_init(|| Regex::new(r"(?s)\{\{.*?\}\}").unwrap())
}

const BASE_HTML: &str = r#"<!doctype html>
<html lang="{{ config.default_language }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ config.title }}{% endblock title %}</title>
  <meta name="description" content="{{ config.description }}">
  <link rel="alternate" type="application/rss+xml" title="{{ config.title }}" href="{{ get_url(path='rss.xml', trailing_slash=false) | safe }}">
  <link rel="alternate" type="application/rss+xml" title="{{ config.title }} podcast" href="{{ get_url(path='podcast.xml', trailing_slash=false) | safe }}">
  <link rel="stylesheet" href="{{ get_url(path='style.css', cachebust=true) }}">
  {% include "notebook_config_head.html" %}
  {% if config.extra.google_analytics_id %}<script async src="https://www.googletagmanager.com/gtag/js?id={{ config.extra.google_analytics_id }}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','{{ config.extra.google_analytics_id }}');</script>{% endif %}
  {% if config.extra.yandex_metrica_id %}<script>window.ym=window.ym||function(){(window.ym.a=window.ym.a||[]).push(arguments)};window.ym.l=1*new Date();</script><script async src="https://mc.yandex.ru/metrika/tag.js"></script><script>ym({{ config.extra.yandex_metrica_id }},'init',{clickmap:true,trackLinks:true,accurateTrackBounce:true});</script>{% endif %}
</head>
<body>
  <header class="site-header">
    <a class="brand" href="{{ config.base_url | safe }}">{{ config.title }}</a>
    <nav>
      {% if config.extra.has_tags_page %}
      <a href="{{ get_url(path='/tags/') }}">Tags</a>
      {% endif %}
      {% if current_path == "/calendar/" %}<span>Calendar</span>{% else %}<a href="{{ get_url(path='/calendar/') }}">Calendar</a>{% endif %}
      {% if config.extra.has_about_page %}
      {% if current_path == "/about/" %}<span>About</span>{% else %}<a href="{{ get_url(path='/about/') }}">About</a>{% endif %}
      {% endif %}
      {% for nav_tag in config.extra.nav_tags %}
      <a href="{{ get_url(path='/tags/' ~ nav_tag.slug ~ '/') | safe }}" title="{{ nav_tag.title }}">#{{ nav_tag.name }}</a>
      {% endfor %}
    </nav>
  {% if config.extra.search_google %}
    <form action="https://www.google.com/search" class="search" method="get"><input name="q" type="search" placeholder="Search"><input name="sitesearch" type="hidden" value="{{ config.base_url }}"></form>
    {% elif config.extra.search_static %}
    <form class="search" role="search"><input id="site-search" type="search" placeholder="Search" autocomplete="off"><ul id="search-results" hidden></ul></form>
    {% endif %}
  </header>
  <main>{% block content %}{% endblock content %}</main>
  {% if config.extra.search_static %}<script src="{{ get_url(path='search_index.en.js') | safe }}"></script><script src="{{ get_url(path='search_metadata.js', cachebust=true) | safe }}"></script><script src="{{ get_url(path='search.js') | safe }}"></script>{% endif %}
  {% if config.extra.has_custom_css %}<link rel="stylesheet" href="{{ get_url(path='custom.css', cachebust=true) }}">{% endif %}
  {% include "notebook_config_body.html" %}
</body>
</html>
"#;

const INDEX_HTML: &str = r#"{% extends "base.html" %}
{% block content %}
{% if config.extra.index_mode == "titles_only" %}
  <ol class="post-list">
  {% for page in paginator.pages %}
    <li><a href="{{ page.permalink | safe }}">{{ page.title }}</a> <time>{{ page.date | date(format="%Y-%m-%d") }}</time></li>
  {% endfor %}
  </ol>
{% else %}
  {% for page in paginator.pages %}
  <article class="post">
    <h2><a href="{{ page.permalink | safe }}">{{ page.title }}</a></h2>
    <p class="meta"><a href="{{ get_url(path='/day/' ~ page.extra.day ~ '/') | safe }}"><time>{{ page.date | date(format="%Y-%m-%d") }}</time></a></p>
    <div class="content">{{ page.content | safe }}</div>
    {% if page.taxonomies.tags %}<p class="tags">{% for tag in page.taxonomies.tags %}<a href="{{ get_taxonomy_url(kind='tags', name=tag) | safe }}">#{{ tag }}</a>{% endfor %}</p>{% endif %}
  </article>
  {% endfor %}
{% endif %}
<nav class="pager">{% if paginator.previous %}<a href="{{ paginator.previous }}">Newer</a>{% endif %}{% if paginator.next %}<a href="{{ paginator.next }}">Older</a>{% endif %}</nav>
{% endblock content %}
"#;

const PAGE_HTML: &str = r#"{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ config.title }}{% endblock title %}
{% block content %}
<article class="post">
  {% if current_path != "/about/" %}
  <h1>{{ page.title }}</h1>
  {% if page.date %}<p class="meta"><time>{{ page.date | date(format="%Y-%m-%d") }}</time></p>{% endif %}
  {% endif %}
  <div class="content">{{ page.content | safe }}</div>
  {% if page.taxonomies.tags %}<p class="tags">{% for tag in page.taxonomies.tags %}<a href="{{ get_taxonomy_url(kind='tags', name=tag) | safe }}">#{{ tag }}</a>{% endfor %}</p>{% endif %}
</article>
{% endblock content %}
"#;

const POST_HTML: &str = r#"{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ config.title }}{% endblock title %}
{% block content %}
<article class='post'>
  <h1>{{ page.title }}</h1>
  {% if page.date %}<p class='meta'><a href='{{ get_url(path="/day/" ~ page.extra.day ~ "/") | safe }}' title='{{ page.date | date(format="%H:%M:%S") }}'><time>{{ page.date | date(format="%Y-%m-%d") }}</time></a></p>{% endif %}
  <div class='content'>{{ page.content | safe }}</div>
  {% if page.taxonomies.tags %}<p class='tags'>{% for tag in page.taxonomies.tags %}<a href='{{ get_taxonomy_url(kind="tags", name=tag) | safe }}'>#{{ tag }}</a>{% endfor %}</p>{% endif %}
</article>
{% if page.higher or page.lower %}
<nav class='post-nav' aria-label='Post navigation'>
  {% if page.higher %}<a class='post-nav__link post-nav__link--prev' href='{{ page.higher.permalink | safe }}' title='{{ page.higher.extra.nav_title }}' accesskey='n' aria-keyshortcuts='Alt+Shift+N' rel='prev'><span>Newer</span><strong>{{ page.higher.title }}</strong></a>{% endif %}
  {% if page.lower %}<a class='post-nav__link post-nav__link--next' href='{{ page.lower.permalink | safe }}' title='{{ page.lower.extra.nav_title }}' accesskey='o' aria-keyshortcuts='Alt+Shift+O' rel='next'><span>Older</span><strong>{{ page.lower.title }}</strong></a>{% endif %}
</nav>
{% endif %}
{% endblock content %}
"#;

const CALENDAR_HTML: &str = r#"{% extends "base.html" %}
{% block title %}Calendar · {{ config.title }}{% endblock title %}
{% block content %}{{ page.content | safe }}{% endblock content %}
"#;

const DAY_HTML: &str = r#"{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ config.title }}{% endblock title %}
{% block content %}<h1>{{ page.title }}</h1><div class="content">{{ page.content | safe }}</div>{% endblock content %}
"#;

const TAGS_LIST_HTML: &str = r#"{% extends "base.html" %}
{% block title %}Tags · {{ config.title }}{% endblock title %}
{% block content %}<h1>Tags</h1><ul class="tag-list">{% for term in terms %}<li><a href="{{ term.permalink | safe }}">#{{ term.name }}</a> <span>{{ term.pages | length }}</span></li>{% endfor %}</ul>{% endblock content %}
"#;

const TAGS_SINGLE_HTML: &str = r#"{% extends "base.html" %}
{% block title %}#{{ term.name }} · {{ config.title }}{% endblock title %}
{% block content %}<h1>#{{ term.name }}</h1><ol class="post-list">{% for page in term.pages %}<li><a href="{{ page.permalink | safe }}">{{ page.title }}</a> <time>{{ page.date | date(format="%Y-%m-%d") }}</time></li>{% endfor %}</ol>{% endblock content %}
"#;

const AUDIO_SHORTCODE: &str =
	r#"<audio controls preload="metadata" src="{{ page.permalink | safe }}{{ src }}"></audio>"#;
const VIDEO_SHORTCODE: &str =
	r#"<video controls preload="metadata" src="{{ page.permalink | safe }}{{ src }}"></video>"#;
const RUFFLE_SHORTCODE: &str = r#"<div class="embed embed-ruffle"><ruffle-player src="{{ page.permalink | safe }}{{ src }}"></ruffle-player><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="Flash file") }}</a></p></div><script src="https://unpkg.com/@ruffle-rs/ruffle"></script>"#;
const MIDI_PLAYER_SHORTCODE: &str = r##"<div class="embed embed-midi"><midi-player src="{{ page.permalink | safe }}{{ src }}" sound-font visualizer="#midi-visualizer-{{ src | slugify }}"></midi-player><midi-visualizer id="midi-visualizer-{{ src | slugify }}" type="piano-roll"></midi-visualizer><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="MIDI file") }}</a></p></div><script src="https://cdn.jsdelivr.net/combine/npm/tone@14.7.77,npm/@magenta/music@1.23.1/es6/core.js,npm/html-midi-player@1.5.0"></script>"##;
const EPUB_VIEWER_SHORTCODE: &str = r#"<details class="attachment-preview attachment-preview-epub embed-epub" data-src="{{ page.permalink | safe }}{{ src }}"><summary>{{ label | default(value="Read EPUB") }}</summary><div class="epub-viewer__frame"></div><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="EPUB") }}</a></p></details><script src="https://cdn.jsdelivr.net/npm/epubjs/dist/epub.min.js"></script><script>for(const el of document.querySelectorAll('.embed-epub[data-src]:not([data-ready])')){el.dataset.ready='1';el.addEventListener('toggle',()=>{if(!el.open||el.dataset.loaded)return;el.dataset.loaded='1';const frame=el.querySelector('.epub-viewer__frame');const book=ePub(el.dataset.src);book.renderTo(frame,{width:'100%',height:'60vh'}).display();});}</script>"#;
const COMIC_VIEWER_SHORTCODE: &str = r#"<details class="attachment-preview attachment-preview-comic embed-comic" data-src="{{ page.permalink | safe }}{{ src }}" data-kind="{{ kind }}"><summary>{{ label | default(value="Read comic") }}</summary><div class="comic-viewer__pages"></div><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="comic") }}</a></p></details><script src="https://cdn.jsdelivr.net/npm/jszip@3.10.1/dist/jszip.min.js"></script><script src="https://cdn.jsdelivr.net/npm/libarchive.js/dist/libarchive.js"></script><script>const imageExt=/\.(avif|gif|jpe?g|png|webp)$/i;async function everpublichComic(el){if(el.dataset.loaded)return;el.dataset.loaded='1';const out=el.querySelector('.comic-viewer__pages');const response=await fetch(el.dataset.src);const data=await response.arrayBuffer();let files=[];if(el.dataset.kind==='cbz'){const zip=await JSZip.loadAsync(data);for(const name of Object.keys(zip.files).sort()){const file=zip.files[name];if(!file.dir&&imageExt.test(name))files.push([name,await file.async('blob')]);}}else{Archive.init({workerUrl:'https://cdn.jsdelivr.net/npm/libarchive.js/dist/worker-bundle.js'});const archive=await Archive.open(new File([data],'comic.cbr'));const extracted=await archive.extractFiles();for(const name of Object.keys(extracted).sort()){const file=extracted[name];if(imageExt.test(name))files.push([name,file.file]);}}for(const [name,blob] of files){const img=document.createElement('img');img.loading='lazy';img.alt=name;img.src=URL.createObjectURL(blob);out.append(img);}}for(const el of document.querySelectorAll('.embed-comic[data-src]:not([data-ready])')){el.dataset.ready='1';el.addEventListener('toggle',()=>{if(el.open)everpublichComic(el).catch(error=>{el.querySelector('.comic-viewer__pages').textContent=error.message;});});}</script>"#;
const FONT_PREVIEW_SHORTCODE: &str = r#"<div class="embed font-preview"><style>@font-face{font-family:'{{ family }}';src:url('{{ page.permalink | safe }}{{ src }}')}</style><p class="font-preview__sample" style="font-family:'{{ family }}'">The quick brown fox jumps over the lazy dog. 0123456789</p><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="font") }}</a></p></div>"#;
const MODEL_VIEWER_SHORTCODE: &str = r#"<div class="embed embed-3d embed-model-viewer"><model-viewer src="{{ page.permalink | safe }}{{ src }}" alt="{{ alt | default(value="3D model") }}" camera-controls touch-action="pan-y" auto-rotate loading="lazy" reveal="interaction"><a href="{{ page.permalink | safe }}{{ src }}" download>Download 3D model</a></model-viewer></div><script type="module" src="https://ajax.googleapis.com/ajax/libs/model-viewer/4.3.1/model-viewer.min.js"></script>"#;
const STL_VIEWER_SHORTCODE: &str = r#"<div class="embed embed-3d embed-stl-viewer stl-viewer" data-src="{{ page.permalink | safe }}{{ src }}" data-label="{{ label | default(value="STL model") }}"><div class="stl-viewer__canvas" role="img" aria-label="{{ label | default(value="STL model") }}"></div><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="STL model") }}</a></p></div><script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.178.0/examples/jsm/"}}</script><script type="module" src="{{ get_url(path='stl-viewer.js', cachebust=true) | safe }}"></script>"#;
const THREE_MODEL_VIEWER_SHORTCODE: &str = r#"<div class="embed embed-3d embed-three-model-viewer three-model-viewer" data-src="{{ page.permalink | safe }}{{ src }}" data-kind="{{ kind }}" data-label="{{ label | default(value="3D model") }}"><div class="three-model-viewer__canvas" role="img" aria-label="{{ label | default(value="3D model") }}"></div><p><a href="{{ page.permalink | safe }}{{ src }}" download>Download {{ label | default(value="3D model") }}</a></p></div><script type="importmap">{"imports":{"three":"https://cdn.jsdelivr.net/npm/three@0.178.0/build/three.module.js","three/addons/":"https://cdn.jsdelivr.net/npm/three@0.178.0/examples/jsm/"}}</script><script type="module" src="{{ get_url(path='three-model-viewer.js', cachebust=true) | safe }}"></script>"#;
const YOUTUBE_SHORTCODE: &str = r#"<div class="embed embed-youtube"><iframe src="https://www.youtube.com/embed/{{ id }}" title="YouTube video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>"#;
const VIMEO_SHORTCODE: &str = r#"<div class="embed embed-vimeo"><iframe src="https://player.vimeo.com/video/{{ id }}" title="Vimeo video" loading="lazy" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>"#;
const SPOTIFY_SHORTCODE: &str = r#"<div class="embed embed-spotify"><iframe src="{{ url }}" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe><a href="{{ url }}">Open in Spotify</a></div>"#;
const SOUNDCLOUD_SHORTCODE: &str = r#"<div class="embed embed-soundcloud"><iframe src="{{ url }}" title="SoundCloud player" loading="lazy" allow="autoplay; encrypted-media"></iframe></div>"#;
const APPLE_PODCAST_SHORTCODE: &str = r#"<div class="embed embed-apple"><iframe src="{{ url }}" loading="lazy" allow="autoplay *; encrypted-media *;"></iframe><a href="{{ url }}">Listen on Apple Podcasts</a></div>"#;
const YANDEX_MUSIC_SHORTCODE: &str = r#"<div class="embed embed-yandex"><iframe src="{{ url }}" loading="lazy"></iframe><a href="{{ url }}">Open in Yandex Music</a></div>"#;
const INSTAGRAM_SHORTCODE: &str = r#"<blockquote class="instagram-media" data-instgrm-permalink="{{ url }}" data-instgrm-version="14"><a href="{{ url }}">View on Instagram</a></blockquote><script async src="//www.instagram.com/embed.js"></script>"#;
const PINTEREST_SHORTCODE: &str = r#"<a data-pin-do="embedPin" data-pin-width="large" href="{{ url }}">View on Pinterest</a><script async defer src="//assets.pinterest.com/js/pinit.js"></script>"#;
const GENIUS_SHORTCODE: &str = r#"<div class='embed embed-genius'><div id='rg_embed_link_{{ song_id }}' class='rg_embed_link' data-song-id='{{ song_id }}'><a href='{{ url }}'>Lyrics on Genius</a></div><script crossorigin src='//genius.com/songs/{{ song_id }}/embed.js'></script></div>"#;
const RUMBLE_SHORTCODE: &str = r#"<div class="embed embed-rumble"><iframe src="https://rumble.com/embed/{{ id }}/" title="Rumble video" loading="lazy" allowfullscreen></iframe></div>"#;
const ODYSEE_SHORTCODE: &str = r#"<div class="embed embed-odysee"><iframe src="{{ url }}" title="Odysee video" loading="lazy" allowfullscreen></iframe></div>"#;
const BILIBILI_SHORTCODE: &str = r#"<div class="embed embed-bilibili"><iframe src="{{ url }}" title="Bilibili video" loading="lazy" allowfullscreen></iframe></div>"#;
const TIKTOK_SHORTCODE: &str = r#"<div class="embed embed-tiktok"><iframe src="https://www.tiktok.com/embed/v2/{{ id }}" title="TikTok video" loading="lazy" allow="encrypted-media" allowfullscreen></iframe><a href="{{ url }}">View on TikTok</a></div>"#;
const STEAM_SHORTCODE: &str = r#"<div class="embed embed-steam"><iframe src="https://store.steampowered.com/widget/{{ app_id }}/" title="Steam app" loading="lazy"></iframe></div>"#;
const VK_PLAYLIST_SHORTCODE: &str = r#"<div class="embed embed-vk-playlist"><iframe src="https://vk.com/widget_playlist.php?oid={{ oid }}&pid={{ pid }}" title="VK playlist" loading="lazy" allow="autoplay; encrypted-media"></iframe></div>"#;

const SEARCH_JS: &str = include_str!("../assets/zola/search.min.js");
const STL_VIEWER_JS: &str = include_str!("../assets/zola/stl-viewer.min.js");
const THREE_MODEL_VIEWER_JS: &str = include_str!("../assets/zola/three-model-viewer.min.js");
const STYLE_CSS: &str = include_str!("../assets/zola/style.min.css");

#[cfg(test)]
mod tests {
	use super::*;
	use crate::evernote::notes_to_posts;
	use crate::evernote::utc;
	use crate::models::{
		BuildState, EvernoteAccessMode, GithubVisibility, Note, Resource, SiteSettings, UserItem,
	};

	#[test]
	fn writes_zola_source_tree_with_podcast() {
		let dir = tempfile::tempdir().unwrap();
		let mut settings = SiteSettings::new("My Site", "everpublich.example");
		settings.github_visibility = GithubVisibility::Private;
		let user = UserItem {
			user_id: "u1".into(),
			registration_date: utc(1_700_000_000),
			evernote_user_id: Some("1".into()),
			evernote_access_mode: EvernoteAccessMode::UserOauth,
			evernote_token: None,
			github_token: None,
			settings,
			build: BuildState::default(),
			deleted_at: None,
		};
		let note = Note {
			guid: "n1".into(),
			title: "Episode".into(),
			created: utc(1_700_000_000),
			updated: utc(1_700_000_000),
			tags: vec!["podcast".into()],
			enml: r#"<en-note><p>Episode intro with &amp; escaped text.</p><en-media type="audio/mpeg" hash="abc"/></en-note>"#.into(),
			resources: vec![Resource {
				hash: "abc".into(),
				file_name: "episode one.mp3".into(),
				original_file_name: None,
				mime: "audio/mpeg".into(),
				s3_key: None,
				text_preview: None,
				archive_tree: None,
				size_bytes: None,
			}],
		};
		let posts = notes_to_posts(&[note], true);
		let generated = write_zola_site(dir.path(), &user, &posts).unwrap();

		assert_eq!(generated.posts, 1);
		assert_eq!(generated.podcast_items, 1);
		assert!(dir.path().join("config.toml").exists());
		assert!(dir.path().join("content/posts/episode/index.md").exists());
		assert!(!dir.path().join("static/stl-viewer.js").exists());
		assert!(!dir.path().join("static/three-model-viewer.js").exists());
		let podcast = fs::read_to_string(dir.path().join("static/podcast.xml")).unwrap();
		assert!(podcast.contains(
			r#"<rss version="2.0" xmlns:itunes="http://www.itunes.com/dtds/podcast-1.0.dtd">"#
		));
		assert!(podcast.contains("<language>en</language>"));
		assert!(podcast.contains("<generator>Everpublich</generator>"));
		assert!(podcast.contains("<itunes:explicit>false</itunes:explicit>"));
		assert!(podcast.contains(
			"<guid isPermaLink=\"true\">https://my-site.everpublich.example/posts/episode/</guid>"
		));
		assert!(
			podcast.contains("<description>Episode intro with &amp; escaped text.</description>")
		);
		assert!(podcast.contains("<itunes:title>Episode</itunes:title>"));
		assert!(podcast.contains("<itunes:author>My Site</itunes:author>"));
		assert!(
			podcast.contains(
				"<itunes:subtitle>Episode intro with &amp; escaped text.</itunes:subtitle>"
			)
		);
		assert!(podcast.contains("<itunes:explicit>false</itunes:explicit>"));
		assert!(podcast.contains(
			"enclosure url=\"https://my-site.everpublich.example/posts/episode/episode%20one.mp3\" type=\"audio/mpeg\" length=\"0\""
		));
		assert!(
			fs::read_to_string(dir.path().join("templates/shortcodes/genius.html"))
				.unwrap()
				.contains("id='rg_embed_link_{{ song_id }}'")
		);
	}

	#[test]
	fn rejects_invalid_podcast_feed() {
		let error = validate_podcast_xml("<rss><channel></channel></rss>", 0)
			.unwrap_err()
			.to_string();

		assert!(error.contains("podcast feed missing iTunes RSS namespace"));
	}

	#[test]
	fn calendar_day_classes_reflect_post_counts() {
		assert_eq!(calendar_day_class(1), "calendar-day calendar-day--one");
		assert_eq!(calendar_day_class(2), "calendar-day calendar-day--two");
		assert_eq!(calendar_day_class(3), "calendar-day calendar-day--many");
		assert_eq!(post_count_label(1), "1 post");
		assert_eq!(post_count_label(3), "3 posts");
	}

	#[test]
	fn reads_config_code_blocks_from_markdown_fences() {
		let blocks = config_code_blocks(
			"widgets: off\n\n```css\nbody { color: red; }\n```\n\n```js\nwindow.ok = true;\n```",
		);

		assert_eq!(blocks.len(), 2);
		assert_eq!(blocks[0].language, "css");
		assert!(blocks[0].body.contains("color: red"));
		assert_eq!(blocks[1].language, "js");
		assert!(blocks[1].body.contains("window.ok"));
	}

	#[test]
	fn calendar_day_title_includes_post_titles() {
		let first = Post {
			guid: "one".into(),
			slug: "one".into(),
			title: "First note".into(),
			date: utc(1_700_000_000),
			tags: vec![],
			body: String::new(),
			resources: vec![],
			kind: PostKind::BlogPost,
		};
		let second = Post {
			title: "Second note".into(),
			..first.clone()
		};
		let posts = vec![&first, &second];

		assert_eq!(
			calendar_day_title(&posts),
			"2 posts\n\nFirst note\n\nSecond note"
		);
		assert_eq!(
			encode_calendar_title_attribute(&calendar_day_title(&posts)),
			"2 posts&#10;&#10;First note&#10;&#10;Second note"
		);
	}

	#[test]
	fn day_archive_title_uses_month_day_and_post_titles() {
		let day = NaiveDate::from_ymd_opt(2023, 11, 15).unwrap();
		let post = Post {
			guid: "one".into(),
			slug: "one".into(),
			title: "Linked Note".into(),
			date: utc(1_700_086_400),
			tags: vec![],
			body: String::new(),
			resources: vec![],
			kind: PostKind::BlogPost,
		};

		assert_eq!(
			day_archive_title(&day, &[&post]),
			"November 15\n\nLinked Note"
		);
		assert_eq!(
			encode_calendar_title_attribute(&day_archive_title(&day, &[&post])),
			"November 15&#10;&#10;Linked Note"
		);
	}
}
