//! Zola source tree generation.

use crate::models::{IndexMode, Post, PostKind, SearchMode, SiteSettings, UserItem};
use anyhow::{Context, Result};
use chrono::{Datelike, NaiveDate};
use html_escape::{encode_double_quoted_attribute, encode_text};
use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

#[derive(Debug, Clone, PartialEq, Eq)]
/// Summary of a generated Zola source tree.
pub struct GeneratedSite {
	/// Zola source root written by the generator.
	pub root: PathBuf,
	/// Number of blog posts written.
	pub posts: usize,
	/// Number of dedicated pages written.
	pub pages: usize,
	/// Number of podcast items written.
	pub podcast_items: usize,
}

/// Write a complete Zola source tree. The caller should run `zola build` and
/// sync `public/` to S3/CloudFront afterwards.
pub fn write_zola_site(root: &Path, user: &UserItem, posts: &[Post]) -> Result<GeneratedSite> {
	fs::create_dir_all(root).with_context(|| format!("failed to create {}", root.display()))?;
	fs::create_dir_all(root.join("content/posts"))?;
	fs::create_dir_all(root.join("content/pages"))?;
	fs::create_dir_all(root.join("templates/shortcodes"))?;
	fs::create_dir_all(root.join("templates/tags"))?;
	fs::create_dir_all(root.join("static"))?;

	write_file(&root.join("config.toml"), &config_toml(&user.settings))?;
	write_file(
		&root.join("content/_index.md"),
		&root_index_md(&user.settings),
	)?;
	write_file(&root.join("content/posts/_index.md"), POSTS_INDEX_MD)?;
	write_templates(root)?;
	write_file(&root.join("static/style.css"), STYLE_CSS)?;
	write_file(&root.join("static/search.js"), SEARCH_JS)?;
	if let Some(custom_css) = user
		.settings
		.custom_css
		.as_deref()
		.filter(|css| !css.trim().is_empty())
	{
		write_file(&root.join("static/custom.css"), custom_css)?;
	}

	let mut post_count = 0;
	let mut page_count = 0;
	let mut day_posts = BTreeMap::<NaiveDate, Vec<&Post>>::new();

	for post in posts {
		match post.kind {
			PostKind::BlogPost => {
				write_post(root, post)?;
				day_posts
					.entry(post.date.date_naive())
					.or_default()
					.push(post);
				post_count += 1;
			}
			PostKind::Page | PostKind::About => {
				write_page(root, post)?;
				page_count += 1;
			}
		}
	}

	write_calendar(root, &day_posts)?;
	write_day_pages(root, &day_posts)?;
	let podcast_items = write_podcast(root, &user.settings, posts)?;

	Ok(GeneratedSite {
		root: root.to_path_buf(),
		posts: post_count,
		pages: page_count,
		podcast_items,
	})
}

fn write_file(path: &Path, content: &str) -> Result<()> {
	if let Some(parent) = path.parent() {
		fs::create_dir_all(parent)?;
	}
	fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))
}

fn config_toml(settings: &SiteSettings) -> String {
	let feeds = "generate_feeds = true\nfeed_filenames = [\"rss.xml\"]\n";
	let theme = settings
		.zola_theme
		.as_ref()
		.map(|t| format!("theme = \"{}\"\n", toml_escape(t)))
		.unwrap_or_default();
	let search = matches!(settings.search_mode, SearchMode::ZolaStatic);
	let google_search = matches!(settings.search_mode, SearchMode::Google);
	let has_custom_css = settings
		.custom_css
		.as_deref()
		.map(|css| !css.trim().is_empty())
		.unwrap_or(false);
	format!(
		r#"# Generated by Everpublich; regenerated on every build.
base_url = "{base_url}"
title = "{title}"
description = "Evernote notebook published as a static Zola website."
default_language = "en"
compile_sass = false
build_search_index = {search}
minify_html = true
{feeds}{theme}
taxonomies = [
  {{ name = "tags", feed = true }},
]

[markdown]
render_emoji = false
external_links_target_blank = true
external_links_no_referrer = true

[extra]
generator = "everpublich"
index_mode = "{index_mode}"
search_static = {search}
search_google = {google_search}
expand_widgets = {expand_widgets}
has_custom_css = {has_custom_css}
google_analytics_id = {google_analytics}
yandex_metrica_id = {yandex_metrica}
"#,
		base_url = toml_escape(&settings.base_url),
		title = toml_escape(&settings.title),
		search = search,
		feeds = feeds,
		theme = theme,
		index_mode = match settings.index_mode {
			IndexMode::FullPosts => "full_posts",
			IndexMode::TitlesOnly => "titles_only",
		},
		google_search = google_search,
		expand_widgets = settings.expand_widgets,
		has_custom_css = has_custom_css,
		google_analytics = option_toml(settings.google_analytics_id.as_deref()),
		yandex_metrica = option_toml(settings.yandex_metrica_id.as_deref()),
	)
}

fn root_index_md(settings: &SiteSettings) -> String {
	let template = if settings.zola_theme.is_none() {
		"template = \"index.html\"\n"
	} else {
		""
	};
	format!("+++\nsort_by = \"date\"\npaginate_by = 20\n{template}+++\n")
}

const POSTS_INDEX_MD: &str = "+++\nsort_by = \"date\"\ntransparent = true\npaginate_by = 20\n+++\n";

fn write_post(root: &Path, post: &Post) -> Result<()> {
	let dir = root.join("content/posts").join(&post.slug);
	let mut md = front_matter(post, Some("page.html"), None);
	md.push_str(&post.body);
	md.push('\n');
	write_file(&dir.join("index.md"), &md)
}

fn write_page(root: &Path, post: &Post) -> Result<()> {
	let name = if post.kind == PostKind::About {
		"about".to_string()
	} else {
		post.slug.clone()
	};
	let dir = root.join("content/pages").join(name);
	let mut md = front_matter(post, Some("page.html"), Some(&post.slug));
	md.push_str(&post.body);
	md.push('\n');
	write_file(&dir.join("index.md"), &md)
}

fn front_matter(post: &Post, template: Option<&str>, path: Option<&str>) -> String {
	let mut out = String::new();
	out.push_str("+++\n");
	let _ = writeln!(out, "title = \"{}\"", toml_escape(&post.title));
	let _ = writeln!(out, "date = {}", post.date.to_rfc3339());
	if let Some(template) = template {
		let _ = writeln!(out, "template = \"{template}\"");
	}
	if let Some(path) = path {
		let _ = writeln!(out, "path = \"{}\"", toml_escape(path));
	}
	let _ = writeln!(out, "slug = \"{}\"", toml_escape(&post.slug));
	out.push_str("\n[taxonomies]\n");
	let tags = post
		.tags
		.iter()
		.map(|t| format!("\"{}\"", toml_escape(t)))
		.collect::<Vec<_>>()
		.join(", ");
	let _ = writeln!(out, "tags = [{tags}]");
	out.push_str("\n[extra]\n");
	let _ = writeln!(out, "guid = \"{}\"", toml_escape(&post.guid));
	let _ = writeln!(out, "day = \"{}\"", post.date.format("%Y-%m-%d"));
	out.push_str("+++\n\n");
	out
}

fn write_calendar(root: &Path, day_posts: &BTreeMap<NaiveDate, Vec<&Post>>) -> Result<()> {
	let mut html = String::new();
	html.push_str(
		"+++\ntitle = \"Calendar\"\npath = \"calendar\"\ntemplate = \"calendar.html\"\n+++\n\n",
	);
	html.push_str("<div class=\"calendar-years\">\n");

	let years = day_posts
		.keys()
		.map(|d| d.year())
		.collect::<BTreeSet<_>>()
		.into_iter()
		.rev()
		.collect::<Vec<_>>();

	for year in years {
		let _ = writeln!(html, "<h2>{year}</h2><div class=\"calendar-months\">");
		for month in 1..=12 {
			let days = day_posts
				.iter()
				.filter(|(day, _)| day.year() == year && day.month() == month)
				.collect::<Vec<_>>();
			if days.is_empty() {
				continue;
			}
			let _ = writeln!(
				html,
				"<section class=\"calendar-month\"><h3>{month:02}</h3><ol>"
			);
			for (day, count) in days {
				let _ = writeln!(
					html,
					"<li><a href=\"/day/{}/\">{} <span>{}</span></a></li>",
					day,
					day.day(),
					count.len()
				);
			}
			html.push_str("</ol></section>\n");
		}
		html.push_str("</div>\n");
	}
	html.push_str("</div>\n");
	write_file(&root.join("content/pages/calendar.md"), &html)
}

fn write_day_pages(root: &Path, day_posts: &BTreeMap<NaiveDate, Vec<&Post>>) -> Result<()> {
	for (day, posts) in day_posts {
		let dir = root.join("content/day").join(day.to_string());
		let mut md = String::new();
		md.push_str("+++\n");
		let _ = writeln!(md, "title = \"{}\"", day);
		let _ = writeln!(md, "path = \"day/{}\"", day);
		md.push_str("template = \"day.html\"\n");
		md.push_str("+++\n\n");
		for post in posts {
			let _ = writeln!(
				md,
				"- [{}](/posts/{}/)",
				encode_text(&post.title),
				post.slug
			);
		}
		write_file(&dir.join("index.md"), &md)?;
	}
	Ok(())
}

fn write_podcast(root: &Path, settings: &SiteSettings, posts: &[Post]) -> Result<usize> {
	let mut items = String::new();
	let mut count = 0usize;
	for post in posts.iter().filter(|post| {
		post.tags
			.iter()
			.any(|tag| tag.eq_ignore_ascii_case("podcast"))
	}) {
		let Some(audio) = post.resources.iter().find(|r| r.mime.starts_with("audio/")) else {
			continue;
		};
		count += 1;
		let url = format!(
			"{}posts/{}/{}",
			settings.base_url,
			post.slug,
			encode_double_quoted_attribute(&audio.file_name)
		);
		let _ = writeln!(
			items,
			"<item><title>{}</title><link>{}posts/{}/</link><guid>{}posts/{}/</guid><pubDate>{}</pubDate><enclosure url=\"{}\" type=\"{}\" length=\"0\"/></item>",
			encode_text(&post.title),
			settings.base_url,
			post.slug,
			settings.base_url,
			post.slug,
			post.date.to_rfc2822(),
			url,
			encode_double_quoted_attribute(&audio.mime),
		);
	}

	let xml = format!(
		r#"<?xml version="1.0" encoding="UTF-8"?>
<rss version="2.0">
<channel>
<title>{}</title>
<link>{}</link>
<description>Podcast feed generated from Evernote notes tagged podcast.</description>
{}
</channel>
</rss>
"#,
		encode_text(&settings.title),
		encode_text(&settings.base_url),
		items
	);
	write_file(&root.join("static/podcast.xml"), &xml)?;
	Ok(count)
}

fn write_templates(root: &Path) -> Result<()> {
	for (path, body) in [
		("templates/base.html", BASE_HTML),
		("templates/index.html", INDEX_HTML),
		("templates/page.html", PAGE_HTML),
		("templates/calendar.html", CALENDAR_HTML),
		("templates/day.html", DAY_HTML),
		("templates/tags/list.html", TAGS_LIST_HTML),
		("templates/tags/single.html", TAGS_SINGLE_HTML),
		("templates/shortcodes/audio.html", AUDIO_SHORTCODE),
		("templates/shortcodes/video.html", VIDEO_SHORTCODE),
		("templates/shortcodes/youtube.html", YOUTUBE_SHORTCODE),
		("templates/shortcodes/vimeo.html", VIMEO_SHORTCODE),
		("templates/shortcodes/spotify.html", SPOTIFY_SHORTCODE),
		(
			"templates/shortcodes/apple_podcast.html",
			APPLE_PODCAST_SHORTCODE,
		),
		(
			"templates/shortcodes/yandex_music.html",
			YANDEX_MUSIC_SHORTCODE,
		),
		("templates/shortcodes/instagram.html", INSTAGRAM_SHORTCODE),
		("templates/shortcodes/pinterest.html", PINTEREST_SHORTCODE),
	] {
		write_file(&root.join(path), body)?;
	}
	Ok(())
}

fn toml_escape(s: &str) -> String {
	s.replace('\\', "\\\\").replace('"', "\\\"")
}

fn option_toml(s: Option<&str>) -> String {
	s.map(|v| format!("\"{}\"", toml_escape(v)))
		.unwrap_or_else(|| "false".to_string())
}

const BASE_HTML: &str = r#"<!doctype html>
<html lang="{{ config.default_language }}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block title %}{{ config.title }}{% endblock title %}</title>
  <meta name="description" content="{{ config.description }}">
  <link rel="alternate" type="application/rss+xml" title="{{ config.title }}" href="{{ get_url(path='rss.xml', trailing_slash=false) | safe }}">
  <link rel="alternate" type="application/rss+xml" title="{{ config.title }} podcast" href="{{ get_url(path='podcast.xml', trailing_slash=false) | safe }}">
  <link rel="stylesheet" href="{{ get_url(path='style.css', cachebust=true) }}">
  {% if config.extra.google_analytics_id %}<script async src="https://www.googletagmanager.com/gtag/js?id={{ config.extra.google_analytics_id }}"></script><script>window.dataLayer=window.dataLayer||[];function gtag(){dataLayer.push(arguments);}gtag('js',new Date());gtag('config','{{ config.extra.google_analytics_id }}');</script>{% endif %}
  {% if config.extra.yandex_metrica_id %}<script>window.ym=window.ym||function(){(window.ym.a=window.ym.a||[]).push(arguments)};window.ym.l=1*new Date();</script><script async src="https://mc.yandex.ru/metrika/tag.js"></script><script>ym({{ config.extra.yandex_metrica_id }},'init',{clickmap:true,trackLinks:true,accurateTrackBounce:true});</script>{% endif %}
</head>
<body>
  <header class="site-header">
    <a class="brand" href="{{ config.base_url | safe }}">{{ config.title }}</a>
    <nav>
      <a href="{{ get_url(path='/tags/') }}">Tags</a>
      <a href="{{ get_url(path='/calendar/') }}">Calendar</a>
      <a href="{{ get_url(path='/about/') }}">About</a>
      <a href="{{ get_url(path='/rss.xml', trailing_slash=false) | safe }}">RSS</a>
    </nav>
  {% if config.extra.search_google %}
    <form action="https://www.google.com/search" class="search" method="get"><input name="q" type="search" placeholder="Search"><input name="sitesearch" type="hidden" value="{{ config.base_url }}"></form>
    {% elif config.extra.search_static %}
    <form class="search" role="search"><input id="site-search" type="search" placeholder="Search" autocomplete="off"><ol id="search-results" hidden></ol></form>
    {% endif %}
  </header>
  <main>{% block content %}{% endblock content %}</main>
  <footer class="site-footer">Generated from Evernote by Everpublich. RSS, sitemap.xml, static search, tags, calendar, media, and podcast feed are included.</footer>
  {% if config.extra.search_static %}<script src="{{ get_url(path='search_index.en.js') | safe }}"></script><script src="{{ get_url(path='search.js') | safe }}"></script>{% endif %}
  {% if config.extra.has_custom_css %}<link rel="stylesheet" href="{{ get_url(path='custom.css', cachebust=true) }}">{% endif %}
</body>
</html>
"#;

const INDEX_HTML: &str = r#"{% extends "base.html" %}
{% block content %}
{% if config.extra.index_mode == "titles_only" %}
  <ol class="post-list">
  {% for page in paginator.pages %}
    <li><a href="{{ page.permalink | safe }}">{{ page.title }}</a> <time>{{ page.date | date(format="%Y-%m-%d") }}</time></li>
  {% endfor %}
  </ol>
{% else %}
  {% for page in paginator.pages %}
  <article class="post">
    <h2><a href="{{ page.permalink | safe }}">{{ page.title }}</a></h2>
    <p class="meta"><a href="{{ get_url(path='/day/' ~ page.extra.day ~ '/') | safe }}"><time>{{ page.date | date(format="%Y-%m-%d") }}</time></a></p>
    <div class="content">{{ page.content | safe }}</div>
    {% if page.taxonomies.tags %}<p class="tags">{% for tag in page.taxonomies.tags %}<a href="{{ get_taxonomy_url(kind='tags', name=tag) | safe }}">#{{ tag }}</a>{% endfor %}</p>{% endif %}
  </article>
  {% endfor %}
{% endif %}
<nav class="pager">{% if paginator.previous %}<a href="{{ paginator.previous }}">Newer</a>{% endif %}{% if paginator.next %}<a href="{{ paginator.next }}">Older</a>{% endif %}</nav>
{% endblock content %}
"#;

const PAGE_HTML: &str = r#"{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ config.title }}{% endblock title %}
{% block content %}
<article class="post">
  <h1>{{ page.title }}</h1>
  {% if page.date %}<p class="meta"><time>{{ page.date | date(format="%Y-%m-%d") }}</time></p>{% endif %}
  <div class="content">{{ page.content | safe }}</div>
  {% if page.taxonomies.tags %}<p class="tags">{% for tag in page.taxonomies.tags %}<a href="{{ get_taxonomy_url(kind='tags', name=tag) | safe }}">#{{ tag }}</a>{% endfor %}</p>{% endif %}
</article>
{% endblock content %}
"#;

const CALENDAR_HTML: &str = r#"{% extends "base.html" %}
{% block title %}Calendar · {{ config.title }}{% endblock title %}
{% block content %}<h1>Calendar</h1>{{ page.content | safe }}{% endblock content %}
"#;

const DAY_HTML: &str = r#"{% extends "base.html" %}
{% block title %}{{ page.title }} · {{ config.title }}{% endblock title %}
{% block content %}<h1>{{ page.title }}</h1><div class="content">{{ page.content | safe }}</div>{% endblock content %}
"#;

const TAGS_LIST_HTML: &str = r#"{% extends "base.html" %}
{% block title %}Tags · {{ config.title }}{% endblock title %}
{% block content %}<h1>Tags</h1><ul class="tag-list">{% for term in terms %}<li><a href="{{ term.permalink | safe }}">#{{ term.name }}</a> <span>{{ term.pages | length }}</span></li>{% endfor %}</ul>{% endblock content %}
"#;

const TAGS_SINGLE_HTML: &str = r#"{% extends "base.html" %}
{% block title %}#{{ term.name }} · {{ config.title }}{% endblock title %}
{% block content %}<h1>#{{ term.name }}</h1><ol class="post-list">{% for page in term.pages %}<li><a href="{{ page.permalink | safe }}">{{ page.title }}</a> <time>{{ page.date | date(format="%Y-%m-%d") }}</time></li>{% endfor %}</ol>{% endblock content %}
"#;

const AUDIO_SHORTCODE: &str =
	r#"<audio controls preload="metadata" src="{{ page.permalink | safe }}{{ src }}"></audio>"#;
const VIDEO_SHORTCODE: &str =
	r#"<video controls preload="metadata" src="{{ page.permalink | safe }}{{ src }}"></video>"#;
const YOUTUBE_SHORTCODE: &str = r#"<div class="embed embed-youtube"><iframe src="https://www.youtube.com/embed/{{ id }}" title="YouTube video" loading="lazy" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div>"#;
const VIMEO_SHORTCODE: &str = r#"<div class="embed embed-vimeo"><iframe src="https://player.vimeo.com/video/{{ id }}" title="Vimeo video" loading="lazy" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe></div>"#;
const SPOTIFY_SHORTCODE: &str = r#"<div class="embed embed-spotify"><iframe src="{{ url }}" loading="lazy" allow="autoplay; clipboard-write; encrypted-media; fullscreen; picture-in-picture"></iframe><a href="{{ url }}">Open in Spotify</a></div>"#;
const APPLE_PODCAST_SHORTCODE: &str = r#"<div class="embed embed-apple"><iframe src="{{ url }}" loading="lazy" allow="autoplay *; encrypted-media *;"></iframe><a href="{{ url }}">Listen on Apple Podcasts</a></div>"#;
const YANDEX_MUSIC_SHORTCODE: &str = r#"<div class="embed embed-yandex"><iframe src="{{ url }}" loading="lazy"></iframe><a href="{{ url }}">Open in Yandex Music</a></div>"#;
const INSTAGRAM_SHORTCODE: &str = r#"<blockquote class="instagram-media" data-instgrm-permalink="{{ url }}" data-instgrm-version="14"><a href="{{ url }}">View on Instagram</a></blockquote><script async src="//www.instagram.com/embed.js"></script>"#;
const PINTEREST_SHORTCODE: &str = r#"<a data-pin-do="embedPin" data-pin-width="large" href="{{ url }}">View on Pinterest</a><script async defer src="//assets.pinterest.com/js/pinit.js"></script>"#;

const SEARCH_JS: &str = r#"(function () {
	const input = document.getElementById('site-search');
	const list = document.getElementById('search-results');
	if (!input || !list || !window.searchIndex) {
		return;
	}
	input.addEventListener('input', function () {
		const query = input.value.trim().toLowerCase();
		list.innerHTML = '';
		if (!query) {
			list.hidden = true;
			return;
		}
		const pages = window.searchIndex.documents || {};
		Object.keys(pages).slice(0, 100).forEach(function (key) {
			const page = pages[key];
			const haystack = ((page.title || '') + ' ' + (page.body || '')).toLowerCase();
			if (haystack.indexOf(query) === -1) {
				return;
			}
			const item = document.createElement('li');
			const link = document.createElement('a');
			link.href = page.url;
			link.textContent = page.title || page.url;
			item.appendChild(link);
			list.appendChild(item);
		});
		list.hidden = list.children.length === 0;
	});
})();
"#;

const STYLE_CSS: &str = include_str!("../assets/zola/style.css");

#[cfg(test)]
mod tests {
	use super::*;
	use crate::evernote::notes_to_posts;
	use crate::evernote::utc;
	use crate::models::{
		BuildState, EvernoteAccessMode, GithubVisibility, Note, Resource, SiteSettings, UserItem,
	};

	#[test]
	fn writes_zola_source_tree_with_podcast() {
		let dir = tempfile::tempdir().unwrap();
		let mut settings = SiteSettings::new("My Site", "everpublich.example");
		settings.github_visibility = GithubVisibility::Private;
		let user = UserItem {
			user_id: "u1".into(),
			registration_date: utc(1_700_000_000),
			evernote_user_id: Some("1".into()),
			evernote_access_mode: EvernoteAccessMode::UserOauth,
			evernote_token: None,
			github_token: None,
			settings,
			build: BuildState::default(),
			deleted_at: None,
		};
		let note = Note {
			guid: "n1".into(),
			title: "Episode".into(),
			created: utc(1_700_000_000),
			updated: utc(1_700_000_000),
			tags: vec!["podcast".into()],
			enml: r#"<en-note><en-media type="audio/mpeg" hash="abc"/></en-note>"#.into(),
			resources: vec![Resource {
				hash: "abc".into(),
				file_name: "episode.mp3".into(),
				mime: "audio/mpeg".into(),
				s3_key: None,
			}],
		};
		let posts = notes_to_posts(&[note], true);
		let generated = write_zola_site(dir.path(), &user, &posts).unwrap();

		assert_eq!(generated.posts, 1);
		assert_eq!(generated.podcast_items, 1);
		assert!(dir.path().join("config.toml").exists());
		assert!(dir.path().join("content/posts/episode/index.md").exists());
		assert!(dir.path().join("static/podcast.xml").exists());
	}
}
